#pragma once

#define FORCE_NKRO
#define MOUSEKEY_DELAY 200
#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_MAX_SPEED 5
#define MOUSEKEY_TIME_TO_MAX 50
#define MOUSEKEY_WHEEL_DELAY 200
#define TAPPING_TERM 150
