AUDIO_ENABLE = no
BACKLIGHT_ENABLE = yes
BLUETOOTH_ENABLE = no
BOOTMAGIC_ENABLE = no
COMMAND_ENABLE = yes
CONSOLE_ENABLE = no
EXTRAKEY_ENABLE = yes
MIDI_ENABLE = no
MOUSEKEY_ENABLE = yes
NKRO_ENABLE = yes
RGBLIGHT_ENABLE = no
SLEEP_LED_ENABLE = no
UNICODE_ENABLE = no

ifndef QUANTUM_DIR
	include ../../../../Makefile
endif
